name:
  'mobile'

environment:
  sdk: '^3.1.0'

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.3.0
  neumorphic_button: ^0.0.1+2
  http: ^0.13.3
  avatar_glow: ^2.0.2

flutter:
  assets:
    - config/
  fonts:
    - family: SofiaSans
      fonts:
        - asset: fonts/SofiaSans/SofiaSans-Medium.ttf
        - asset: fonts/SofiaSans/SofiaSans-MediumItalic.ttf
        - asset: fonts/SofiaSans/SofiaSans-SemiBold.ttf
        - asset: fonts/SofiaSans/SofiaSans-Bold.ttf
  uses-material-design: true